### ISSUE TITLE
Представление ударения в леммах

### ISSUE THREAD

**Issue by bzaar** [gramdict/zalizniak-2010#1]
Варианты:

1. `Титика́ка ж 3а`
2. `Титикака 6 ж 3а`

Первый вариант проще читать, второй проще набирать. Во втором проще искать заданное слово инструментами, которые "не понимают" ударения. Например, Google Chrome понимает. А Word, Excel, Ron's editor, EmEditor - нет.

Как во втором варианте представить статьи типа:

* `Золота́я Орда́ п + ж 1d—`

Можно, например, так:

* `Золотая Орда 6+4 п + ж 1d—`

**Comment by bzaar** [comment]
Я склоняюсь ко второму варианту, т.к. увы... техника еще не дошла. В принципе, преобразование между этими двумя вариантами тривиально. Когда дойдет, можем перейти к первому.

**Comment by bzaar** [comment]
Есть еще вариант типа 3. `Титика/ка`. Его проще набирать, чем №1, но с поиском те же проблемы, даже хуже.

**Comment by ghost** [comment]
Конечно, 2.

А "эталонный словарь" будет какого издания? 6-го?

**Comment by bzaar** [comment]
@opennota , «Грамматический словарь» (шестое издание) опубликован в этом репозитории.

**Comment by bzaar** [comment]
@opennota 

Насчет ударения, пока оставил вариант 1 – он гораздо легче читается, чем 2. 

Вариант 1 имеет недостатки: 

* Не все программы имеют опцию игнорировать знаки ударения при поиске (Хром с этим хорошо справляется). Завел также [тикет](https://youtrack.jetbrains.com/issue/IDEA-265071) для Intellij IDEA.
* Не очень удобно набирать знаки ударения (числа в варианте 2, впрочем, тоже). Хорошо, что в словаре всегда под рукой много ударных букв, которые можно скопировать. Еще рекомендую [раскладку Ильи Бирмана](https://ilyabirman.ru/projects/typography-layout/) для PC/Mac. В ней знак основного ударения вводится нажатием Ctrl-Shift-Alt-/ два раза, побочного –  Ctrl-Shift-Alt-` два раза. Также в некоторых программах (MS Word) знаки ударения вводятся с помощью Alt+768, Alt+769 (удерживая левый Alt, ввести цифры на _цифровой_ клавиатуре при включенном NumLock).

В целом хочется думать, что техника будет двигаться в направлении поддержки знаков ударения и использование варианта 1 будет все более оправданным.

Если у кого-то есть сильные аргументы в пользу того или иного варианта, можем пересмотреть и поменять.
