### ISSUE TITLE
обня́ться, подня́ться, разня́ться, отня́ться missing △?

### ISSUE THREAD

**Issue by bzaar** [gramdict/zalizniak-2010#13]
Why do `/b` verbs have △ before _`прош. м`_ and `/c''` verbs don't?

наня́ться св 14b/b (найм-) △ _прош. м_ нанялся́ //наня́лся ◑II(нанима́ться)
обня́ться св 14c/c'' (-им-), _прош. м_ обня́лся //обнялся́ ◑II(обнима́ться)
подня́ться св 14c/c'' (подним- //подым-), _прош. м_ подня́лся //поднялся́ ◑II(поднима́ться //подыма́ться)
разня́ться св 14c/c'' (-им-), _прош. м_ разня́лся //разнялся́ ◑II(разнима́ться)
приня́ться св 14c/b (прим-) △ _прош. м_ принялся́ //приня́лся ◑II(принима́ться)
отня́ться св 14c/c'' (-им-), _прош. м_ отня́лся //отнялся́ ◑II(отнима́ться)

**Comment by shenyileirob** [comment]
By the way, a type-14 verb is said to be always accompanied by a present stem notation like (-н-), (-м-), (-им-) or something else, which is lacking in «отсня́ться св 14с/c''». This entry is not included in Zaliznjak (1980), but according to [Russian Wiktionary](https://ru.wiktionary.org/wiki/%D0%BE%D1%82%D1%81%D0%BD%D1%8F%D1%82%D1%8C%D1%81%D1%8F), (-им-) is expected here.

**Comment by bzaar** [comment]
@shenyileirob - thanks, I believe this deserves its own issue: raised #17.

**Comment by shenyileirob** [comment]
A `/c''` normally expands to two m.sg past forms, one with the stress before the reflexive suffix, and the other, which is labelled _устар._, with the stress on the reflexive suffix. Here probably Zaliznjak just wanted to say that the forms spelt out are not irregular themselves, but both forms are in current use?

**Comment by bzaar** [comment]
@shenyileirob  Yes, the _`прош. м.`_ label is there to override the _`устар.`_ label implied by `/c''`. Still, why do `/b` verbs have △ before _`прош. м`_ and `/c''` verbs don't?

**Comment by shenyileirob** [comment]
@bzaar Because regular reflexive `/b` verbs don't have the variation in the m.sg past, innit?

**Comment by bzaar** [comment]
@shenyileirob True, they don't, but that's not a reason for omitting △ in `/c''` verbs. The triangle (△) introduces irregular forms, i.e. those that don't match the forms derived from the 'index':

> Указания за знаком △. За этим знаком приводятся морфологически нерегулярные формы (т. е. те, которые отклоняются от общих правил склонения и спряжения, содержащихся в разделах о значении индексов). Практически это означает, что они отклоняются от того табличного образца, который соответствует индексу данного слова.

https://gramdict.ru/howtouse#triangle

Such is the case for `/b` verbs:

* наня́ться св 14b/b (найм-) △ _прош. м_ нанялся́//наня́лся 

The past m.sg. derived from the index would be `наня́лся` which doesn't match `нанялся́//наня́лся`. This is irregular and warrants the △.

* обня́ться св 14c/c'' (-им-), _прош. м_ обня́лся//обнялся́

The past m.sg. derived from the index would be `обня́лся//`_`устар.`_` обнялся́` which (if you squint) matches `обня́лся//обнялся́` up to the _`устар.`_ qualifier.

So there we are. In the first case, the past m. sg. is considered irregular, and in the second case it's sort of regular, removing the need for △.

Looks like I've answered my own question.
