### ISSUE TITLE
уня́ться: 14b/c''?

### ISSUE THREAD

**Issue by shenyileirob** [gramdict/zalizniak-2010#21]
The present database gives `14b/c` for **уня́ться**. However, both [English](https://en.wiktionary.org/wiki/%D1%83%D0%BD%D1%8F%D1%82%D1%8C%D1%81%D1%8F) and [Russian](https://ru.wiktionary.org/wiki/%D1%83%D0%BD%D1%8F%D1%82%D1%8C%D1%81%D1%8F) Wiktionary give `14b/c''`, which is supported by Ushakov (1935):

> уйму́сь, уймёшься, _прош._ я́лся́, яла́сь; уня́вшийся, _сов._ (_к_ униматься).

Note also that `/c` and `/c''` are in perfect complementary distribution, with `/c` for non-reflexive verbs and `/c''` for reflexive verbs, disregarding the very entry in question.

**Comment by bzaar** [comment]
Zaliznjak, 1987:

![image](https://user-images.githubusercontent.com/4028922/213488782-347870fb-03af-4672-8394-3a662b63e201.png)

Zaliznjak, 2010 (colouring mine):

![image](https://user-images.githubusercontent.com/4028922/213487300-e249fb5e-c3ca-4aae-a4cb-dbd46246673f.png)
