### ISSUE TITLE
отчленя́ть is `нсв` instead of `св`

### ISSUE THREAD

**Issue by shenyileirob** [gramdict/zalizniak-2010#23]
Both the present database and my scanned copy of Zaliznjak (1980) show `св` for __отчленя́ть__, but it is actually the `нсв` counterpart of the `св` __отчлени́ть__.

**Comment by bzaar** [comment]
Indeed. From 2010:

![image](https://user-images.githubusercontent.com/4028922/213884710-6705b302-0963-4fa7-b113-b2bed28438a2.png)
