### ISSUE TITLE
Wrong opposite aspect notations for сжева́ть and уволо́чь

### ISSUE THREAD

**Issue by shenyileirob** [gramdict/zalizniak-2010#24]
> сжева́ть св 2b, ё ◑1
> уволо́чь св 8b/b (-к-) [//_простореч._ __уволочи́ть__] ◑1(-а-)

`◑1` here should be `◑I` (-> сжёвывать, увола́кивать).

` св .*◑[0-9]` matches no more apart from those already mentioned in #19 and #23. ` нсв .*◑I` matches nothing.

**Comment by bzaar** [comment]
These errors are present in Zaliznjak, 2010:

![image](https://user-images.githubusercontent.com/4028922/213884394-01a0ac6b-47e0-4f62-8352-51fcd941ce62.png)

![image](https://user-images.githubusercontent.com/4028922/213884443-b2e388e3-808a-4a3d-b565-139647888e68.png)
