### ISSUE TITLE
Unpaired parenthesis in сто́лько

### ISSUE THREAD

**Issue by shenyileirob** [gramdict/zalizniak-2010#25]
> сто́лько [...] мс (_столь многое_ [_без указания предмета_]: я́ сто́льким Ва́м обя́зан, о сто́льком переговори́ли _и т. п.), Р._ сто́льк|ого, _Д._ -ому, _Т._ -им, _П._ -ом, _В.=И._)

Unpaired closing parenthesis. Sub-entry absent from Zaliznjak (1980).

**Comment by bzaar** [comment]
@shenyileirob  Can I ask you to raise separate issues for each entry? That way, they're easier to discuss, reference and label. E.g. __Бельфа́ст__ here would be an `ocr-error` while the other two are `2010-bug`s.

**Comment by bzaar** [comment]
Zaliznjak, 2010:

![image](https://user-images.githubusercontent.com/4028922/213930108-9f1612a4-b7ce-4a5f-adec-281861536ee0.png)

![image](https://user-images.githubusercontent.com/4028922/213930083-d693afbe-a473-40e1-98dd-624a19655de7.png)

**Comment by bzaar** [comment]
@shenyileirob 

In __столько__, we obviously need to remove the last parethesis.

What do you think the correct entry should look like for __всходить__?

**Comment by shenyileirob** [comment]
@bzaar I see why you would like separate issues to be raised for EACH entry. **всходи́ть** is now split into a separate issue #37.
