### ISSUE TITLE
Жи́ль Бла́з

### ISSUE THREAD

**Issue by shenyileirob** [gramdict/zalizniak-2010#26]
**Жи́ль Бла́з**, stress mark on `a` instead of on `л`. See #9.

**Comment by bzaar** [comment]
Жи́ль Бл́аз is clearly annotated with two acute accents:

![image](https://user-images.githubusercontent.com/4028922/210186332-1dce1412-32db-41bf-bd9e-ed29fa53aa29.png)

No change is necessary.

_Originally posted by @bzaar in https://github.com/gramdict/zalizniak-2010/issues/9#issuecomment-1368553464_
