### ISSUE TITLE
зо́ркость is `8a` instead of `8з`

### ISSUE THREAD

**Issue by shenyileirob** [gramdict/zalizniak-2010#32]
`8з` is ill-formed. My Zaliznjak (1980) and both Wiktionaries show `8a`.

**Comment by bzaar** [comment]
Zaliznjak 2010:

![image](https://user-images.githubusercontent.com/4028922/213920399-d25d1e96-3d92-4e57-bf79-b55e6423f05b.png)

**Comment by bzaar** [comment]
Zaliznjak, 1987:

![image](https://user-images.githubusercontent.com/4028922/213921162-2d594602-b5a6-4b6b-841e-65011ecc84ff.png)
