### ISSUE TITLE
`◑I(-а́-)` <- `◑I(-а-)`

### ISSUE THREAD

**Issue by shenyileirob** [gramdict/zalizniak-2010#33]
The following 5 `св`s have (sub)regular `◑I(-а́-)` `нсв` counterparts but are unexpectedly given `◑I(-а-)`, a label not mentioned in Zaliznjak's introduction:
- 2/закоси́ть	◑зака́шивать
- своло́чь	◑свола́кивать
- отволо́чь	◑отвола́кивать
- уволо́чь	◑увола́кивать
- вы́волочь	◑вывола́кивать

**Comment by bzaar** [comment]
Zaliznjak, 1987:

![image](https://user-images.githubusercontent.com/4028922/213923929-d1b116de-3db3-451b-ba57-c8386c950446.png)

Zaliznjak, 2010:

![image](https://user-images.githubusercontent.com/4028922/213924020-dcd6e7f7-2767-4503-9066-6e86830c6c57.png)

Zaliznjak, 1987:

![image](https://user-images.githubusercontent.com/4028922/213923988-e3ee0fce-64fe-4874-9f36-5684fe7969b2.png)

Zaliznjak, 2010:

![image](https://user-images.githubusercontent.com/4028922/213924069-bbfc8de6-677a-4791-8349-c670758d8b8d.png)
