### ISSUE TITLE
Unpaired parenthesis in обега́ть

### ISSUE THREAD

**Issue by shenyileirob** [gramdict/zalizniak-2010#34]
> обега́ть [...] нсв 1a (_бежать, минуя что-л._ ◑5(обежа́ть)

Unpaired opening parethesis. Paired with ...`что-л._) ◑5`... in Zaliznjak (1980).

**Comment by bzaar** [comment]
Zaliznjak, 2010:

![image](https://user-images.githubusercontent.com/4028922/213922934-db1218ce-c99f-475c-a58b-331136a2a713.png)
