### ISSUE TITLE
Unpaired bracket in пеше́чком

### ISSUE THREAD

**Issue by shenyileirob** [gramdict/zalizniak-2010#35]
> пеше́чком н [//__пешо́чком__] (_см._)]

Unpaired closing bracket. ...`[//__пешо́чком__ (_см._)]` in Zaliznjak (1980).

**Comment by bzaar** [comment]
Zaliznjak, 1987:

![image](https://user-images.githubusercontent.com/4028922/213922304-6a471a45-dd8f-4da4-9c16-fd98f1feebf9.png)

Zaliznjak, 2010:

![image](https://user-images.githubusercontent.com/4028922/213922377-a008b026-bdac-4e03-b2bb-4516bb502567.png)
