### ISSUE TITLE
чихну́ть: intransitive verb marked with `✕`

### ISSUE THREAD

**Issue by shenyileirob** [gramdict/zalizniak-2010#36]
> чихну́ть св нп 3b✕

**чихну́ть** seems the only intransitive verb in the database marked with `✕`, which means the formation of its past passive participle (henceforth ppp) is difficult. But an intransitive verb has no ppp in nature.

This `✕` is already present in Zaliznjak (1980).

**Comment by bzaar** [comment]
Zaliznjak, 2010: 

![image](https://user-images.githubusercontent.com/4028922/213933918-2b0590d4-42b3-45c2-9193-2df994675336.png)

**Comment by bzaar** [comment]
Ruscorpora.ru [doesn't give](https://ruscorpora.ru/results?search=CusBEs4BCssBEmEKFwoDbGV4EhAKDtGH0LjRhdC90YPRgtGMCgoKBGZvcm0SAgoACgsKBWdyYW1tEgIKAAoJCgNzZW0SAgoAChUKB3NlbS1tb2QSCgoIc2VtfHNlbXgKCwoFZmxhZ3MSAgoAEmYKCQoDbGV4EgIKAAoKCgRmb3JtEgIKAAoQCgVncmFtbRIHCgUoYWNjKQoJCgNzZW0SAgoAChUKB3NlbS1tb2QSCgoIc2VtfHNlbXgKCwoFZmxhZ3MSAgoACgwKBGRpc3QiBAgBEAEqEQoICAAQChgyIAoaAQMgAEAFMgIIAToBBDAB) any examples of чихнуть governing an accusative. (It can be followed by an accusative as in «чихнул раз-другой» but that, of course, is not the same as governing.)

The verb __прочихнуть__ only appears in the main corpus twice, with one occurrence governing an accusative:

*  Корбах сильно прочихнул свою слизь в мягкие ткани, после чего решил к Степаниде на коленях не ползти, а просто пойти в этот театр в качестве нормального зрителя. [Василий Аксенов. Новый сладостный стиль (1997)]
*  И, скажу вам, засуха стояла тогда такая, что никто и не запомнит; в воздухе не то дым, не то туман, пахнет гарью, мгла, солнце, как ядро раскаленное, а что пыля ― не прочихнешь! [И. С. Тургенев. Собака (1847-1852)]
