### ISSUE TITLE
золотно́й: missing stem type `1`

### ISSUE THREAD

**Issue by shenyileirob** [gramdict/zalizniak-2010#39]
> золотно́й п b⌧ [//__золо́тный__]

Obviously the stem type of `1` is missing. **золотно́й** is absent from Zaliznjak (1980).

**Comment by bzaar** [comment]
Zaliznjak, 2010:

![image](https://user-images.githubusercontent.com/4028922/214324810-5a708cac-5f5e-425e-b69b-c2aa442427a2.png)
