### ISSUE TITLE
Сам словарь

### ISSUE THREAD

**Issue by gasyoun** [gramdict/zalizniak-2010#4]
Словаря файл не вижу я один?

**Comment by bzaar** [comment]
Да, этот репозиторий несколько заброшен. Когда-то завел его для обсуждения проблем, связанных с "Грамматическим словарем". Сейчас репозиторий потерял актуальность. Наверное, стоит его удалить.

Если вас интересует словарь Зализняка, вот его официальный сайт: http://gramdict.ru

**Comment by gasyoun** [comment]
Спасибо, не знал про https://github.com/morpher-ru/gramdict/issues. А где писать вопросы по неточности морфера, скажите, пожалуйста?

**Comment by bzaar** [comment]
Про неточности морфера лучше всего писать здесь:
http://morpher.ru/Forum/Bugs.aspx

Я вам написал письмо в личку (с вашего сайта).

**Comment by bzaar** [comment]
Теперь сам словарь опубликован в этом репозитории.
