### ISSUE TITLE
`колготи́ться нсв 4a`?

### ISSUE THREAD

**Issue by shenyileirob** [gramdict/zalizniak-2010#46]
Or `4b`, as the [Russian Wiktionary](https://ru.wiktionary.org/wiki/%D0%BA%D0%BE%D0%BB%D0%B3%D0%BE%D1%82%D0%B8%D1%82%D1%8C%D1%81%D1%8F) and [Reznichenko (2003)](http://slovana.ru/slovari/reznichenko/orfoepicheskij-slovar-reznichenko_0439.htm) show? (**колготи́ться** is absent from Zaliznjak (1980).)

**Comment by bzaar** [comment]
Zaliznjak (2010):

![image](https://user-images.githubusercontent.com/4028922/218260015-87e9adbe-92be-42d0-8a69-71cd36a50a62.png)

**Comment by bzaar** [comment]
Yes, `4a` would give `колго́чусь, колго́тишься, колго́тится`:

![image](https://user-images.githubusercontent.com/4028922/218260273-ba3cb1eb-f56b-479e-8e23-17b498148d6a.png)

which is obviously incorrect.

It should be `4b`: `колгочу́сь, колготи́шься, колготи́тся`.
