### ISSUE TITLE
⑨ в статье ГНЕСТИ

### ISSUE THREAD

**Issue by damartyan** [gramdict/zalizniak-2010#5]
Мне кажется, что ⑨ в статье ГНЕСТИ стоит по ошибке, эта помета относится только к глаголам совершенного вида. В издании 1980 года её нет. Видимо, на каком-то этапе редактирования словаря она появилась по аналогии с приставочными однокоренными глаголами совершенного вида.

гнести́ нсв 7b/b (-т-)⑨, ё
нагнести́ св 7b/b (-т-)⑨, ё ◑II
пригнести́ св 7b/b (-т-)⑨, ё ◑II
сгнести́ св 7b/b (-т-)⑨, ё ◑II
угнести́ св 7b/b (-т-)⑨, ё (все формы, кроме прич. страд., устар.) ◑II

**Comment by bzaar** [comment]
Действительно, как сказано в [Грамматических сведениях](https://gramdict.ru/conjugation#verb-circle-9):

> Помета ⑨ встречается у глаголов совершенного вида и означает, что у данного глагола в роли деепр. прош. выступает форма на **-я (-а)**, образованная от основы буд. времени по правилам для деепр. наст. Регулярно образованное деепр. прош. при этом также существует, но в современном языке неупотребительно. Пример:
>
> привезти́	св 7b / b⑨, ё — _деепр. прош._ привезя́ [// _устар._ привёзши].

Имеется ли эта девятка в печатном издании 2010 года? Если нет, то просто удалить ее из этого репозитория. Если есть, то, скорее всего, это ошибка. Тогда предлагаю завести две ветки: одну отражающую печатное издание, другую с исправлениями.

Или у кого-то есть предположения, что эта девятка могла появиться неслучайно?

В ruscorpora.ru нет ни _гнетя_, ни _гнётши_.

**Comment by bzaar** [comment]
В издании 2010 года ⑨ есть:

![image](https://user-images.githubusercontent.com/4028922/139534253-af353a98-a13a-4d14-902a-35dd895f4762.png)

**Comment by bzaar** [comment]
Подтверждаю, что в издании 1977 г. девятки в статье ГНЕСТИ нет:

![image](https://user-images.githubusercontent.com/4028922/159715392-bb308897-21ae-40ea-8a30-0930d47578ef.png)
