### ISSUE TITLE
Забыты главные ударения (одѝннадцатилетний, ѝзосиллабизм)

### ISSUE THREAD

**Issue by NiMixail** [gramdict/zalizniak-2010#50]
Заметил, что в этих двух словах отмечено только побочное ударение. Нужно: одѝннадцатиле́тний, ѝзосиллаби́зм

(P.S. если это читает Нияз Киреев, привет, я был в новозаветном проекте по типологии :) )

**Comment by bzaar** [comment]
Спасибо, что сообщили о найденных ошибках!

В издании 2010 года нужные ударения присутствуют:

![image](https://github.com/gramdict/zalizniak-2010/assets/4028922/3e380a5c-dec4-49f4-905f-55c0d261f88a)

![image](https://github.com/gramdict/zalizniak-2010/assets/4028922/0497bd07-42ff-4429-8a12-754765547128)
