### ISSUE TITLE
наст. for св обокра́сть?

### ISSUE THREAD

**Issue by shenyileirob** [gramdict/zalizniak-2010#54]
`обокра́сть св 7b (-д-) △ _наст._ обкраду́`...

**Comment by bzaar** [comment]
What seems to be the issue here? For reference, the full entry currently reads:

> __обокра́сть__ св 7b (-д-) △ _наст._ обкраду́, -ёт [//обокраду́, -ёт]; _прич. страд._ обкра́денный//обокра́денный ◑I(обкра́дывать)

**Comment by shenyileirob** [comment]
@bzaar It should be буд. rather than наст. for a св verb, right?

**Comment by bzaar** [comment]
Yes, that's right. Thanks for raising this issue. It's like this in Zaliznjak-2010:

![image](https://github.com/user-attachments/assets/cc9a518d-a901-477c-bc7a-7c90f4faa6e3)
